# Generated by Django 5.1.3 on 2025-02-07 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_profile_delete_userprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="zipcode",
        ),
    ]
