# Generated by Django 5.1.3 on 2025-02-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="slots",
            name="date",
            field=models.DateField(default="2025-02-27"),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="slots",
            unique_together={("date", "start_time")},
        ),
    ]
