# Generated by Django 5.1.3 on 2025-03-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_slots_date_alter_slots_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeletedOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_id", models.IntegerField()),
                ("customer_name", models.CharField(max_length=255)),
                ("service_date", models.DateTimeField()),
                ("deleted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "deleted_orders",
            },
        ),
    ]
